modLoader="javafml"
loaderVersion="[40,)"
license="MIT License"
issueTrackerURL="https://github.com/onVoid/EnderitesDelight/issues"


[[mods]]
modId="enderitesdelight"
version="${file.jarVersion}"
displayName="Enderite's Delight"
displayURL="https://www.curseforge.com/minecraft/mc-mods/enderites-delight"
updateJSONURL="https://onvoid.net/enderitesdelight/update.json"
logoFile="enderitesdelight.png"
logoBlur=false
credits="vectorwing - Farmer's Delight creator"
authors="brdle"
description="Adds an Enderite Knife to Farmer's Delight."
itemIcon="enderitesdelight:enderite_knife"
configBackground="minecraft:textures/block/bricks.png"

[[dependencies.enderitesdelight]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.enderitesdelight]]
    modId="farmersdelight"
    mandatory=true
    versionRange="[1.18.2-1.0.4,]"
    ordering="AFTER"
    side="BOTH"

[[dependencies.enderitesdelight]]
    modId="lolenderite"
    mandatory=true
    versionRange="[1.4-1.18.2,]"
    ordering="AFTER"
    side="BOTH"